# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
#orbs:
#  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.3.1

jobs:
  ivycode:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: build & deploy
          command: |
            ./run ci

workflows:
  version: 2
  build-deploy:
    jobs:
      - firstTap:
          filters:
            branches:
              only: master
